# When enabled, this allows shorter env properties (ex -Dspring.profiles.active=xray)
spring:
  main:
    # ZipkinXRayStorageModule overrides the bean named 'storage'
    allow-bean-definition-overriding: true
zipkin:
  internal:
    module:
      xray: zipkin.module.storage.xray.ZipkinXRayStorageModule
  storage:
    xray:
      # Amazon X-Ray Daemon UDP daemon address; defaults to localhost:2000
      daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}
