# This file is in the ./docker directory as otherwise it is mistaken for a GitHub Workflow

version: "3.6"
services:
  # TODO: this will pass because X-Ray just sends UDP at the moment.
  # Authenticate and use the other modules: sqs,kinesis,elasticsearch-aws

  # Use fixed service and container name 'sut; so our test script can copy/pasta
  sut:
    # This is the image just built. It is not in a remote repository.
    image: openzipkin/zipkin-aws:test
    container_name: sut
    environment:
      - STORAGE_TYPE=xray
