# When enabled, this allows shorter env properties (ex -Dspring.profiles.active=elasticsearch-aws)
spring:
  main:
    # ZipkinElasticsearchAwsStorageModule overrides the bean named 'storage'
    allow-bean-definition-overriding: true
zipkin:
  internal:
    module:
      elasticsearch-aws: zipkin.module.storage.elasticsearch.aws.ZipkinElasticsearchAwsStorageModule
  storage:
    elasticsearch:
      aws:
        domain: ${ES_AWS_DOMAIN:}
        region: ${ES_AWS_REGION:${AWS_REGION:}}
