# When enabled, this allows shorter env properties (ex -Dspring.profiles.active=elasticsearch-aws)
spring:
  main:
    # ZipkinElasticsearchAwsStorageAutoConfiguration overrides the bean named 'storage'
    allow-bean-definition-overriding: true
zipkin:
  storage:
    elasticsearch:
      aws:
        domain: ${ES_AWS_DOMAIN:}
        region: ${ES_AWS_REGION:}
